### ISSUE TITLE
All S3 buckets deleted when passing MIRROR_TARGET=""

### ISSUE THREAD

**Issue by lachiejames** [peter-evans/s3-backup#10]
I tried out this action at work today, and accidentally passed an empty string to MIRROR_TARGET.  Later I noticed that an important S3 bucket had been deleted.  I went through the CloudTrail logs to find the knucklehead that did this, and saw that the bucket was deleted when I ran this action with the empty string.

I tried to reproduce this issue on my personal AWS account by creating a dummy bucket called `aaaaa-first-bucket` so that it would be shown at the top of the list, and then ran the same action to see if the bucket would be deleted.  

But something worse happened.  ALL OF MY S3 BUCKETS WERE DELETED!!!

Thankfully I didn't have anything too important on my personal account, but this could be catastrophic for other developers.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/47808687/196694300-5ed81457-7cea-42f4-9713-56296d7bf560.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/47808687/196693608-4a401f64-a1d2-49c9-aa9f-a270314bd307.png">

This is the configuration I used:

```
jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MIRROR_TARGET: ""
        with:
          args: --overwrite --remove
```
