### ISSUE TITLE
Does this include all branches / history?

### ISSUE THREAD

**Issue by adrianpaiva1** [peter-evans/s3-backup#5]
Sorry if this is a stupid question, but does this backup all of my branches / commit history?

I have it setup like the example, to run on push of the master branch.

**Comment by peter-evans** [comment]
Hi @adrianpaiva1 

It just copies whatever files are available locally. If you want the entire git history then you need to make sure that is available locally when the action runs.

If you are using the checkout action it will only checkout one branch. So you probably won't have everything you need locally.
```yml
- uses: actions/checkout@v2
```

I'm not 100% sure how to make sure the `.git` folder contains all the information it needs to recover completely, but you would definitely need to checkout all the branches with full commit history, and all the tags. If you figure out the git commands to get a completely recoverable local copy, please let me know.

**Comment by aegershman** [comment]
Hey @peter-evans + @adrianpaiva1 I think what you need is `fetch-depth: 0`:

[From the `actions/checkout` docs](https://github.com/actions/checkout)

>    Number of commits to fetch. 0 indicates all history for all branches and tags.
>    Default: 1
>    fetch-depth: ''

Additionally, specifically, this section: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

Try this out:

```yml
jobs:
  repository-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.MIRROR_TARGET }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        with:
          args: --overwrite --remove
```
